/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AlunoDAO;
import dao.UtilitarioDAO;
import java.awt.Dimension;
import model.Aluno;
import util.Formata;
import static util.Formata.carregaEstadoCivil;
import static util.Formata.carregaFormacao;
import static util.Formata.carregaSexo;
import static util.Formata.carregaUF;
import static util.Formata.retornarEstadoCivil;
import static util.Formata.retornarFormacao;
import static util.Formata.retornarSexo;
import static util.Formata.retornarUf;

/**
 *
 * @author Henrique Vieira
 */
public class TelaCadastroDeAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroDeAlunos
     */

    public TelaCadastroDeAluno() {
        initComponents();
        setMascara();
        carregaSexo(cbSexoAluno);
        carregaEstadoCivil(cbEstCivilAluno);
        carregaFormacao(cbFormacaoAluno);
        carregaUF(cbUfAluno);
        carregaUF(cbUfRG);
        carregaUF(cbUfRGResAluno);
        limpaTela();
    }

    private void setMascara() {
        ftxtCpfAluno.setFormatterFactory(Formata.cpf());
        ftxtTelefoneAluno.setFormatterFactory(Formata.telefone());
        ftxtCelularAluno.setFormatterFactory(Formata.celular());
        ftxtCepAluno.setFormatterFactory(Formata.cep());
        ftxtDTNascAluno.setFormatterFactory(Formata.data());
        ftxtCpfResAluno.setFormatterFactory(Formata.cpf());
        ftxtDTNascResAluno.setFormatterFactory(Formata.data());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCódigoAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ftxtTelefoneAluno = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ftxtCelularAluno = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmailAluno = new javax.swing.JTextField();
        btBuscarAluno = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ftxtCepAluno = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLogradouroAluno = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumAluno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtComAluno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtbairroAluno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCidAluno = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbUfAluno = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ftxtDTNascAluno = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNatAluno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbEstCivilAluno = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtProfAluno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ftxtCpfAluno = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRGAluno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbUfRG = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbSexoAluno = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtNomeMaeAluno = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNomePaiAluno = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtnomeResAluno = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ftxtCpfResAluno = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        txtRGResAluno = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cbUfRGResAluno = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        ftxtDTNascResAluno = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        cbFormacaoAluno = new javax.swing.JComboBox<>();
        btLimparAluno = new javax.swing.JButton();
        btSalvarAluno = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Aluno");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Principal"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Código:");

        jLabel4.setText("Telefone:");

        try {
            ftxtTelefoneAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Celular:");

        try {
            ftxtCelularAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Email:");

        btBuscarAluno.setText("Buscar");
        btBuscarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCódigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeAluno))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(ftxtTelefoneAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(ftxtCelularAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(txtEmailAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCódigoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftxtTelefoneAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ftxtCelularAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmailAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel7.setText("CEP:");

        jLabel8.setText("Logradouro:");

        jLabel9.setText("Nº:");

        jLabel10.setText("Complemento:");

        jLabel11.setText("Bairro:");

        jLabel12.setText("Cidade:");

        jLabel13.setText("UF:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(ftxtCepAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(txtLogradouroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(txtComAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3)
                        .addComponent(txtbairroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)
                        .addGap(2, 2, 2)
                        .addComponent(txtCidAluno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumAluno)
                    .addComponent(cbUfAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftxtCepAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtLogradouroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtComAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtbairroAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtCidAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbUfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLabel14.setText("Data Nascimento:");

        jLabel15.setText("Naturalidade:");

        jLabel16.setText("Estado Civil:");

        jLabel17.setText("Profissão:");

        jLabel18.setText("CPF:");

        jLabel19.setText("Identidade:");

        jLabel20.setText("UF:");

        jLabel21.setText("Sexo:");

        jLabel22.setText("Nome da Mãe:");

        jLabel23.setText("Nome do Pai:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Caso Menor de Idade - Cadastro Responsável Financeiramente"));

        jLabel24.setText("Nome do Responsável:");

        jLabel25.setText("CPF:");

        jLabel26.setText("Identidade:");

        jLabel27.setText("UF:");

        jLabel29.setText("Data de Nascimento:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(4, 4, 4)
                .addComponent(txtnomeResAluno))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(4, 4, 4)
                        .addComponent(ftxtCpfResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(3, 3, 3)
                        .addComponent(txtRGResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(cbUfRGResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(3, 3, 3)
                        .addComponent(ftxtDTNascResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtnomeResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ftxtCpfResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtRGResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(cbUfRGResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(ftxtDTNascResAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jLabel30.setText("Formação:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(ftxtCpfAluno))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(ftxtDTNascAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addComponent(txtNatAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(3, 3, 3)
                        .addComponent(txtRGAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16)
                        .addGap(3, 3, 3)
                        .addComponent(cbEstCivilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel17)
                        .addGap(4, 4, 4)
                        .addComponent(txtProfAluno))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(cbUfRG, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSexoAluno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeMaeAluno)
                            .addComponent(txtNomePaiAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(9, 9, 9)
                        .addComponent(cbFormacaoAluno, 0, 213, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ftxtDTNascAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtNatAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbEstCivilAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtProfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ftxtCpfAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtRGAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cbUfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cbSexoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(txtNomeMaeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomePaiAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(cbFormacaoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btLimparAluno.setText("Limpar");
        btLimparAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparAlunoActionPerformed(evt);
            }
        });

        btSalvarAluno.setText("Salvar");
        btSalvarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimparAluno)
                .addGap(18, 18, 18)
                .addComponent(btSalvarAluno)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarAluno)
                    .addComponent(btLimparAluno))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparAlunoActionPerformed
        limpaTela();
    }//GEN-LAST:event_btLimparAlunoActionPerformed

    private void btSalvarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarAlunoActionPerformed
        AlunoDAO daoA = new AlunoDAO();
        UtilitarioDAO utilDAO = new UtilitarioDAO();
        Aluno sAluno = new Aluno();
        sAluno.setNome(txtNomeAluno.getText());
        sAluno.setCidade(txtCidAluno.getText());
        sAluno.setComplementoLogradouro(txtComAluno.getText());
        sAluno.setEmail(txtEmailAluno.getText());
        sAluno.setLogradouro(txtLogradouroAluno.getText());
        sAluno.setNaturalidade(txtNatAluno.getText());
        sAluno.setNomeMae(txtNomeMaeAluno.getText());
        sAluno.setNomePai(txtNomePaiAluno.getText());
        sAluno.setNumlogradouro(Integer.parseInt(txtNumAluno.getText()));
        sAluno.setProfissao(txtProfAluno.getText());
        sAluno.setRg(txtRGAluno.getText());
        sAluno.setRgResponsavel(txtRGResAluno.getText());
        sAluno.setBairro(txtbairroAluno.getText());
        sAluno.setNomeResponsavel(txtnomeResAluno.getText());
        sAluno.setCelular(ftxtCelularAluno.getText());
        sAluno.setCep(ftxtCepAluno.getText());
        sAluno.setCpf(ftxtCpfAluno.getText());
        sAluno.setCpfResponsavel(ftxtCpfResAluno.getText());
        sAluno.setDataNascimento(ftxtDTNascAluno.getText());
        sAluno.setDataNascResponsavel(ftxtDTNascResAluno.getText());
        sAluno.setTelefone(ftxtTelefoneAluno.getText());
        sAluno.setEstadoCivil(cbEstCivilAluno.getSelectedItem().toString());
        sAluno.setFormacao(cbFormacaoAluno.getSelectedItem().toString());
        sAluno.setSexo(cbSexoAluno.getSelectedItem().toString());
        sAluno.setUfLogradouro(cbUfAluno.getSelectedItem().toString());
        sAluno.setUfRg(cbUfRG.getSelectedItem().toString());
        sAluno.setUfRGResponsavel(cbUfRGResAluno.getSelectedItem().toString());
        daoA.insert(sAluno);
        utilDAO.retornaIDCadastrado("aluno");
    }//GEN-LAST:event_btSalvarAlunoActionPerformed

    private void btBuscarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarAlunoActionPerformed
        AlunoDAO daoB = new AlunoDAO();
        Aluno bAluno =  daoB.findByCodigo(Integer.parseInt(txtCódigoAluno.getText()));
        txtNomeAluno.setText(bAluno.getNome());
        txtCidAluno.setText(bAluno.getCidade());
        txtComAluno.setText(bAluno.getComplementoLogradouro());
        txtEmailAluno.setText(bAluno.getEmail());
        txtLogradouroAluno.setText(bAluno.getLogradouro());
        txtNatAluno.setText(bAluno.getNaturalidade());
        txtNomeMaeAluno.setText(bAluno.getNomeMae());
        txtNomePaiAluno.setText(bAluno.getNomePai());
        txtNumAluno.setText(bAluno.getNumlogradouro() + "");
        txtProfAluno.setText(bAluno.getProfissao());
        txtRGAluno.setText(bAluno.getRg());
        txtRGResAluno.setText(bAluno.getRgResponsavel());
        txtbairroAluno.setText(bAluno.getBairro());
        txtnomeResAluno.setText(bAluno.getNomeResponsavel());
        ftxtCelularAluno.setText(bAluno.getCelular());
        ftxtCepAluno.setText(bAluno.getCep());
        ftxtCpfAluno.setText(bAluno.getCpf());
        ftxtCpfResAluno.setText(bAluno.getCpfResponsavel());
        ftxtDTNascAluno.setText(bAluno.getDataNascimento());
        ftxtDTNascResAluno.setText(bAluno.getDataNascResponsavel());
        ftxtTelefoneAluno.setText(bAluno.getTelefone());
        retornarEstadoCivil(cbEstCivilAluno,bAluno.getEstadoCivil());
        retornarFormacao(cbFormacaoAluno,bAluno.getFormacao());
        retornarSexo(cbSexoAluno,bAluno.getSexo());
        retornarUf(cbUfAluno,bAluno.getUfLogradouro());
        retornarUf(cbUfRG,bAluno.getUfRg());
        retornarUf(cbUfRGResAluno,bAluno.getUfRGResponsavel());
    }//GEN-LAST:event_btBuscarAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarAluno;
    private javax.swing.JButton btLimparAluno;
    private javax.swing.JButton btSalvarAluno;
    private javax.swing.JComboBox<String> cbEstCivilAluno;
    private javax.swing.JComboBox<String> cbFormacaoAluno;
    private javax.swing.JComboBox<String> cbSexoAluno;
    private javax.swing.JComboBox<String> cbUfAluno;
    private javax.swing.JComboBox<String> cbUfRG;
    private javax.swing.JComboBox<String> cbUfRGResAluno;
    private javax.swing.JFormattedTextField ftxtCelularAluno;
    private javax.swing.JFormattedTextField ftxtCepAluno;
    private javax.swing.JFormattedTextField ftxtCpfAluno;
    private javax.swing.JFormattedTextField ftxtCpfResAluno;
    private javax.swing.JFormattedTextField ftxtDTNascAluno;
    private javax.swing.JFormattedTextField ftxtDTNascResAluno;
    private javax.swing.JFormattedTextField ftxtTelefoneAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField txtCidAluno;
    private javax.swing.JTextField txtComAluno;
    private javax.swing.JTextField txtCódigoAluno;
    private javax.swing.JTextField txtEmailAluno;
    private javax.swing.JTextField txtLogradouroAluno;
    private javax.swing.JTextField txtNatAluno;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeMaeAluno;
    private javax.swing.JTextField txtNomePaiAluno;
    private javax.swing.JTextField txtNumAluno;
    private javax.swing.JTextField txtProfAluno;
    private javax.swing.JTextField txtRGAluno;
    private javax.swing.JTextField txtRGResAluno;
    private javax.swing.JTextField txtbairroAluno;
    private javax.swing.JTextField txtnomeResAluno;
    // End of variables declaration//GEN-END:variables
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void limpaTela(){
        txtCidAluno.setText("");
        txtComAluno.setText("");
        txtCódigoAluno.setText("");
        txtEmailAluno.setText("");
        txtLogradouroAluno.setText("");
        txtNatAluno.setText("");
        txtNomeMaeAluno.setText("");
        txtNomePaiAluno.setText("");
        txtNomeAluno.setText("");
        txtNumAluno.setText("0");
        txtProfAluno.setText("");
        txtRGAluno.setText("");
        txtRGResAluno.setText("");
        txtbairroAluno.setText("");
        txtnomeResAluno.setText("");
        ftxtCelularAluno.setText("");
        ftxtCepAluno.setText("");
        ftxtCpfAluno.setText("");
        ftxtCpfResAluno.setText("");
        ftxtDTNascAluno.setText("");
        ftxtDTNascResAluno.setText("");
        ftxtTelefoneAluno.setText("");
        cbEstCivilAluno.setSelectedIndex(0);
        cbFormacaoAluno.setSelectedIndex(0);
        cbSexoAluno.setSelectedIndex(0);
        cbUfAluno.setSelectedIndex(0);
        cbUfRG.setSelectedIndex(0);
        cbUfRGResAluno.setSelectedIndex(0);
    }
}
