/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AlunoDAO;
import dao.FuncionarioDAO;
import java.awt.Dimension;
import model.Funcionario;
import util.Formata;
import static util.Formata.carregaCargo;
import static util.Formata.carregaEstadoCivil;
import static util.Formata.carregaFormacao;
import static util.Formata.carregaSexo;
import static util.Formata.carregaUF;
import static util.Formata.retornarEstadoCivil;
import static util.Formata.retornarFormacao;
import static util.Formata.retornarSexo;
import static util.Formata.retornarUf;
import static util.Formata.retornarCargo;


/**
 *
 * @author CarlosHVChaves
 */
public class TelaCadastroDeFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroDeProfessor
     */
    public TelaCadastroDeFuncionario() {
        initComponents();
        setMascara();
        carregaSexo(cbSexoFuncionario);
        carregaEstadoCivil(cbEstCivilFuncionario);
        carregaFormacao(cbFormacaoFuncionario);
        carregaUF(cbUfFuncionario);
        carregaUF(cbUfRGFuncionario);
        carregaCargo(cbCargoContratadoFuncionario); 
        limpaTela();

    }

    private void setMascara() {
        ftxtCpfFuncionario.setFormatterFactory(Formata.cpf());
        ftxtTelefoneFuncionario.setFormatterFactory(Formata.telefone());
        ftxtCelularFuncionario.setFormatterFactory(Formata.celular());
        ftxtCepFuncionario.setFormatterFactory(Formata.cep());
        ftxtDTNascFuncionario.setFormatterFactory(Formata.data());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCódigoFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ftxtTelefoneFuncionario = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ftxtCelularFuncionario = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmailFuncionario = new javax.swing.JTextField();
        btBuscarFuncionario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ftxtCepFuncionario = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLogradouroFuncionario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNumFuncionario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtComFuncionario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtbairroFuncionario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCidFuncionario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbUfFuncionario = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ftxtDTNascFuncionario = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNatFuncionario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbEstCivilFuncionario = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ftxtCpfFuncionario = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRGFuncionario = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbUfRGFuncionario = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cbSexoFuncionario = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txtNomeMaeFuncionario = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNomePaiFuncionario = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        cbFormacaoFuncionario = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        cbCargoContratadoFuncionario = new javax.swing.JComboBox<>();
        btLimparFuncionario = new javax.swing.JButton();
        btSalvarFuncionario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Funcionário");

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Principal"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Código:");

        jLabel4.setText("Telefone:");

        try {
            ftxtTelefoneFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Celular:");

        try {
            ftxtCelularFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Email:");

        btBuscarFuncionario.setText("Buscar");
        btBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCódigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuscarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(ftxtTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(ftxtCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(txtEmailFuncionario))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtCódigoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftxtTelefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ftxtCelularFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel7.setText("CEP:");

        jLabel8.setText("Logradouro:");

        jLabel9.setText("Nº:");

        jLabel10.setText("Complemento:");

        jLabel11.setText("Bairro:");

        jLabel12.setText("Cidade:");

        jLabel13.setText("UF:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(2, 2, 2)
                        .addComponent(ftxtCepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(txtLogradouroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(txtComFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3)
                        .addComponent(txtbairroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)
                        .addGap(2, 2, 2)
                        .addComponent(txtCidFuncionario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumFuncionario)
                    .addComponent(cbUfFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ftxtCepFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtLogradouroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtComFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtbairroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtCidFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cbUfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLabel14.setText("Data Nascimento:");

        jLabel15.setText("Naturalidade:");

        jLabel16.setText("Estado Civil:");

        jLabel18.setText("CPF:");

        jLabel19.setText("Identidade:");

        jLabel20.setText("UF:");

        jLabel21.setText("Sexo:");

        jLabel22.setText("Nome da Mãe:");

        jLabel23.setText("Nome do Pai:");

        jLabel30.setText("Formação:");

        jLabel17.setText("Cargo Contratado:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(ftxtCpfFuncionario))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(2, 2, 2)
                        .addComponent(ftxtDTNascFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addComponent(txtNatFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(3, 3, 3)
                        .addComponent(txtRGFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel16)
                        .addGap(3, 3, 3)
                        .addComponent(cbEstCivilFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(cbUfRGFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbSexoFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(6, 6, 6)
                        .addComponent(txtNomeMaeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomePaiFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFormacaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCargoContratadoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ftxtDTNascFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtNatFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbEstCivilFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ftxtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtRGFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(cbUfRGFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(cbSexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNomeMaeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)
                        .addComponent(txtNomePaiFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(cbFormacaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cbCargoContratadoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btLimparFuncionario.setText("Limpar");
        btLimparFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparFuncionarioActionPerformed(evt);
            }
        });

        btSalvarFuncionario.setText("Salvar");
        btSalvarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLimparFuncionario)
                .addGap(18, 18, 18)
                .addComponent(btSalvarFuncionario)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparFuncionario)
                    .addComponent(btSalvarFuncionario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparFuncionarioActionPerformed
        limpaTela();
    }//GEN-LAST:event_btLimparFuncionarioActionPerformed

    private void btSalvarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarFuncionarioActionPerformed
        FuncionarioDAO dao = new FuncionarioDAO();
        Funcionario sFuncionario = new Funcionario();
        sFuncionario.setNome(txtNomeFuncionario.getText());
        sFuncionario.setCidade(txtCidFuncionario.getText());
        sFuncionario.setComplementoLogradouro(txtComFuncionario.getText());
        sFuncionario.setEmail(txtEmailFuncionario.getText());
        sFuncionario.setLogradouro(txtLogradouroFuncionario.getText());
        sFuncionario.setNaturalidade(txtNatFuncionario.getText());
        sFuncionario.setNomeMae(txtNomeMaeFuncionario.getText());
        sFuncionario.setNomePai(txtNomePaiFuncionario.getText());
        sFuncionario.setNumlogradouro(Integer.parseInt(txtNumFuncionario.getText()));
        sFuncionario.setRg(txtRGFuncionario.getText());
        sFuncionario.setBairro(txtbairroFuncionario.getText());
        sFuncionario.setCelular(ftxtCelularFuncionario.getText());
        sFuncionario.setCep(ftxtCepFuncionario.getText());
        sFuncionario.setCpf(ftxtCpfFuncionario.getText());
        sFuncionario.setDataNascimento(ftxtDTNascFuncionario.getText());
        sFuncionario.setTelefone(ftxtTelefoneFuncionario.getText());
        sFuncionario.setEstadoCivil(cbEstCivilFuncionario.getSelectedItem().toString());
        sFuncionario.setFormacao(cbFormacaoFuncionario.getSelectedItem().toString());
        sFuncionario.setSexo(cbSexoFuncionario.getSelectedItem().toString());
        sFuncionario.setUfLogradouro(cbUfFuncionario.getSelectedItem().toString());
        sFuncionario.setUfRg(cbUfRGFuncionario.getSelectedItem().toString());
        sFuncionario.setCargo(cbCargoContratadoFuncionario.getSelectedItem().toString());
        dao.insert(sFuncionario);
        dao.findByCpf(ftxtCpfFuncionario.getText());
    }//GEN-LAST:event_btSalvarFuncionarioActionPerformed

    private void btBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarFuncionarioActionPerformed
        FuncionarioDAO daoF = new FuncionarioDAO();
        Funcionario bFuncionario =  daoF.findByCodigo(Integer.parseInt(txtCódigoFuncionario.getText()));
        txtNomeFuncionario.setText(bFuncionario.getNome());
        txtCidFuncionario.setText(bFuncionario.getCidade());
        txtComFuncionario.setText(bFuncionario.getComplementoLogradouro());
        txtEmailFuncionario.setText(bFuncionario.getEmail());
        txtLogradouroFuncionario.setText(bFuncionario.getLogradouro());
        txtNatFuncionario.setText(bFuncionario.getNaturalidade());
        txtNomeMaeFuncionario.setText(bFuncionario.getNomeMae());
        txtNomePaiFuncionario.setText(bFuncionario.getNomePai());
        txtNumFuncionario.setText(bFuncionario.getNumlogradouro() + "");
        txtRGFuncionario.setText(bFuncionario.getRg());
        txtbairroFuncionario.setText(bFuncionario.getBairro());
        ftxtCelularFuncionario.setText(bFuncionario.getCelular());
        ftxtCepFuncionario.setText(bFuncionario.getCep());
        ftxtCpfFuncionario.setText(bFuncionario.getCpf());
        ftxtDTNascFuncionario.setText(bFuncionario.getDataNascimento());
        ftxtTelefoneFuncionario.setText(bFuncionario.getTelefone());
        retornarEstadoCivil(cbEstCivilFuncionario,bFuncionario.getEstadoCivil());
        retornarFormacao(cbFormacaoFuncionario,bFuncionario.getFormacao());
        retornarSexo(cbSexoFuncionario,bFuncionario.getSexo());
        retornarUf(cbUfFuncionario,bFuncionario.getUfLogradouro());
        retornarUf(cbUfRGFuncionario,bFuncionario.getUfRg());
        retornarCargo(cbCargoContratadoFuncionario,bFuncionario.getCargo());
    }//GEN-LAST:event_btBuscarFuncionarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarFuncionario;
    private javax.swing.JButton btLimparFuncionario;
    private javax.swing.JButton btSalvarFuncionario;
    private javax.swing.JComboBox<String> cbCargoContratadoFuncionario;
    private javax.swing.JComboBox<String> cbEstCivilFuncionario;
    private javax.swing.JComboBox<String> cbFormacaoFuncionario;
    private javax.swing.JComboBox<String> cbSexoFuncionario;
    private javax.swing.JComboBox<String> cbUfFuncionario;
    private javax.swing.JComboBox<String> cbUfRGFuncionario;
    private javax.swing.JFormattedTextField ftxtCelularFuncionario;
    private javax.swing.JFormattedTextField ftxtCepFuncionario;
    private javax.swing.JFormattedTextField ftxtCpfFuncionario;
    private javax.swing.JFormattedTextField ftxtDTNascFuncionario;
    private javax.swing.JFormattedTextField ftxtTelefoneFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField txtCidFuncionario;
    private javax.swing.JTextField txtComFuncionario;
    private javax.swing.JTextField txtCódigoFuncionario;
    private javax.swing.JTextField txtEmailFuncionario;
    private javax.swing.JTextField txtLogradouroFuncionario;
    private javax.swing.JTextField txtNatFuncionario;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtNomeMaeFuncionario;
    private javax.swing.JTextField txtNomePaiFuncionario;
    private javax.swing.JTextField txtNumFuncionario;
    private javax.swing.JTextField txtRGFuncionario;
    private javax.swing.JTextField txtbairroFuncionario;
    // End of variables declaration//GEN-END:variables
    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    public void limpaTela(){
        cbEstCivilFuncionario.setSelectedIndex(0);
        cbFormacaoFuncionario.setSelectedIndex(0);
        cbSexoFuncionario.setSelectedIndex(0);
        cbUfFuncionario.setSelectedIndex(0);
        cbUfRGFuncionario.setSelectedIndex(0);
        ftxtCelularFuncionario.setText("");
        ftxtCepFuncionario.setText("");
        ftxtCpfFuncionario.setText("");
        ftxtDTNascFuncionario.setText("");
        ftxtTelefoneFuncionario.setText("");
        txtCidFuncionario.setText("");
        txtComFuncionario.setText("");
        txtCódigoFuncionario.setText("");
        txtEmailFuncionario.setText("");
        txtLogradouroFuncionario.setText("");
        txtNatFuncionario.setText("");
        txtNomeMaeFuncionario.setText("");
        txtNomePaiFuncionario.setText("");
        txtNomeFuncionario.setText("");
        txtNumFuncionario.setText("0");
        txtRGFuncionario.setText("");
        txtbairroFuncionario.setText("");
    }
}
